name: app
description: The PREPARED mobile app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.1+21

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  json_schema: ^5.1.1
  shared_preferences: ^2.1.2
  webview_flutter: 4.2.3
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.2
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  cloud_firestore: ^4.8.3
  device_info_plus: ^10.1.2
  flutter_chat_bubble: ^2.0.2
  provider: ^6.0.5
  uuid: ^4.4.2
  chewie: ^1.8.1
  video_player: ^2.8.6
  intl: ^0.18.1
  package_info_plus: ^7.0.0
  native_device_orientation: ^2.0.3
  gap: ^3.0.1
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.1
  internet_connection_checker_plus: ^2.2.0
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

  # Enables launcher icons, see: https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/prepared_icon_724x724.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/help/
    - assets/onboarding/
    - assets/icon/
    - assets/images/
    - assets/schema/
    - assets/story/
    - assets/secrets/
