// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:app/secrets.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // initialise options using values from secrets file in assets

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Secrets.getSecret('firebase-web-apiKey'),
    appId: Secrets.getSecret('firebase-web-appId'),
    messagingSenderId: Secrets.getSecret('firebase-web-messagingSenderId'),
    projectId: Secrets.getSecret('firebase-web-projectId'),
    authDomain: Secrets.getSecret('firebase-web-authDomain'),
    storageBucket: Secrets.getSecret('firebase-web-storageBucket'),
    measurementId: Secrets.getSecret('firebase-web-measurementId'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Secrets.getSecret('firebase-android-apiKey'),
    appId: Secrets.getSecret('firebase-android-appId'),
    messagingSenderId: Secrets.getSecret('firebase-android-messagingSenderId'),
    projectId: Secrets.getSecret('firebase-android-projectId'),
    storageBucket: Secrets.getSecret('firebase-android-storageBucket'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Secrets.getSecret('firebase-ios-apiKey'),
    appId: Secrets.getSecret('firebase-ios-appId'),
    messagingSenderId: Secrets.getSecret('firebase-ios-messagingSenderId'),
    projectId: Secrets.getSecret('firebase-ios-projectId'),
    storageBucket: Secrets.getSecret('firebase-ios-storageBucket'),
    iosClientId: Secrets.getSecret('firebase-ios-iosClientId'),
    iosBundleId: Secrets.getSecret('firebase-ios-iosBundleId'),
  );
}
